package enumerators;

public enum EclipxEnumerator {

	ECLIPX_USERNAME_LOCATOR,
	ECLIPX_PASSWORD_LOCATOR,
	ECLIPX_LOGIN_LOCATOR,
	ECLIPX_NEWQUOTE_BUTTON,
	ECLIPX_PRODUCT_DROPDOWN,
	ECLIPX_CAR_DROPDOWN,
	ECLIPX_ERROR_MESSAGE
}
