package enumerators;

public enum LoginPageEnumerator {
    SIGN_IN_LINK_TEXT_XPATH,
    EMAIL_ID_TEXTBOX_XPATH,
    PASSWORD_TEXTBOX_XPATH,
    SIGN_IN_IN_BUTTON_XPATH,
    SIGN_OUT_LINK_TEXT_XPATH,
    ERROR_MESSAGE_SPAN_XPATH,
    ERROR_MESSAGE_FOR_INVALID_PASSWORD
}
