package enumerators;

public enum SearchProductEnumerator {
    SIZE_MENU_XPATH_LOCATOR,
    SIZE_8_MENU_XPATH_LOCATOR,
    SEARCHED_PRODUCT_ITEM_LIST_XPATH_LOCATOR,
    SEARCHED_PRODUCT_PARENT_CONTAINER_XPATH_LOCATOR,
    INDIVITUAL_PRODUCT_SIZE_CHART_XPATH_LOCATOR,
    OFFER_SOCKS_PRODUCT_XPATH,
    OFER_SOCKS_PRODUCT_CATOGORY_XPATH,
    EMAIL_SIGNUP_POPUP_NO_THANK_YOU_XPATH,
    SIZE_SEARCHED_PRODUCT_ITEM_SCROLL_TO_VIEW_XPATH,
    OFFER_SOCKS_PRODUCT_LIST_XPATH
}
